### ISSUE TITLE
OpenCL source build error in ultima

### ISSUE THREAD

**Issue by telmin** [fixstars/clpy#48]
Hi

I got error in ultima when kernel compiling.
Could you give some advice please...

thanks.

- System information
    - Ubuntu 16.04
    - CUDA 9.2
    - Geforce GTX1080Ti

- error message.
```
======================================================================
ERROR: test_argmax (__main__.TestNdarray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ndarray.py", line 160, in test_argmax
    y = x.argmax()
  File "clpy/core/core.pyx", line 1000, in clpy.core.core.ndarray.argmax
  File "clpy/core/core.pyx", line 1009, in clpy.core.core.ndarray.argmax
  File "clpy/core/reduction.pxi", line 269, in clpy.core.core.simple_reduction_function.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/carray.pxi", line 174, in clpy.core.core.compile_with_cache
  File "clpy/core/reduction.pxi", line 94, in clpy.core.core._get_simple_reduction_kernel
  File "clpy/core/carray.pxi", line 158, in clpy.core.core.compile_with_cache
  File "clpy/core/carray.pxi", line 174, in clpy.core.core.compile_with_cache
clpy.backend.ultima.exceptions.UltimaRuntimeError: Return code:-6
STDERR:
ultima: /root/llvm/llvm/tools/clang/lib/AST/DeclBase.cpp:840: const AttrVec& clang::Decl::getAttrs() const: Assertion `HasAttrs && "No attrs to get!"' failed.

```

- backtrace

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffeceb0801 in __GI_abort () at abort.c:79
#2  0x00007fffecea039a in __assert_fail_base (fmt=0x7fffed0277d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x271fd10 "HasAttrs && \"No attrs to get!\"", file=file@entry=0x271ea90 "/root/llvm/llvm/tools/clang/lib/AST/DeclBase.cpp", line=line@entry=840, function=function@entry=0x2725240 <clang::Decl::getAttrs() const::__PRETTY_FUNCTION__> "const AttrVec& clang::Decl::getAttrs() const") at assert.c:92
#3  0x00007fffecea0412 in __GI___assert_fail (assertion=0x271fd10 "HasAttrs && \"No attrs to get!\"", file=0x271ea90 "/root/llvm/llvm/tools/clang/lib/AST/DeclBase.cpp", line=840, function=0x2725240 <clang::Decl::getAttrs() const::__PRETTY_FUNCTION__> "const AttrVec& clang::Decl::getAttrs() const") at assert.c:101
#4  0x00000000017972dc in clang::Decl::getAttrs (this=0x372aca0) at /root/llvm/llvm/tools/clang/lib/AST/DeclBase.cpp:840
#5  0x000000000042a428 in clang::Decl::getAttrs (this=0x0) at /home/sakamoto/libs/llvm/include/clang/AST/DeclBase.h:478
#6  ultima::decl_visitor::prettyPrintPragmas<clang::VarDecl> (this=0x36090a0, D=0x0) at ultima.cpp:1831
#7  0x0000000000414519 in ultima::decl_visitor::VisitVarDecl (this=0x36090a0, D=0x372aca0, parameter=true) at ultima.cpp:2588
#8  0x0000000000412020 in ultima::decl_visitor::VisitParmVarDecl (this=<optimized out>, D=<optimized out>) at ultima.cpp:2740
#9  ultima::decl_visitor::VisitFunctionDecl (this=0x36090a0, D=0x372b0c0) at ultima.cpp:2343
#10 0x000000000040f7da in ultima::decl_visitor::VisitFunctionTemplateDecl (this=0x36090a0, D=<optimized out>) at ultima.cpp:2970
#11 0x0000000000426fea in ultima::decl_visitor::VisitDeclContext (this=<optimized out>, DC=<optimized out>, indent=false) at ultima.cpp:2045
#12 0x00000000009c767f in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false) at /root/llvm/llvm/tools/clang/lib/Parse/ParseAST.cpp:159
#13 0x000000000051d401 in clang::ASTFrontendAction::ExecuteAction (this=0x360bdd0) at /root/llvm/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:999
#14 0x000000000051ce16 in clang::FrontendAction::Execute (this=0x360bdd0) at /root/llvm/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:897
#15 0x00000000004b0168 in clang::CompilerInstance::ExecuteAction (this=0x7fffffffca40, Act=...) at /root/llvm/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:991
#16 0x00000000004506a0 in clang::tooling::FrontendActionFactory::runInvocation (this=0x36018c0, Invocation=std::shared_ptr<clang::CompilerInvocation> (empty) = {...}, Files=0x36012d0, PCHContainerOps=std::shared_ptr<clang::PCHContainerOperations> (empty) = {...}, DiagConsumer=0x0) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:323
#17 0x00000000004504c6 in clang::tooling::ToolInvocation::runInvocation (this=0x7fffffffd6b0, BinaryName=0x3603ee0 "clang-tool", Compilation=0x3604e80, Invocation=std::shared_ptr<clang::CompilerInvocation> (empty) = {...}, PCHContainerOps=std::shared_ptr<clang::PCHContainerOperations> (empty) = {...}) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:299
#18 0x00000000004502cf in clang::tooling::ToolInvocation::run (this=0x7fffffffd6b0) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:284
#19 0x0000000000451956 in clang::tooling::ClangTool::run (this=0x7fffffffd8f0, Action=0x36018c0) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:456
#20 0x000000000040cf5f in main (argc=<optimized out>, argv=<optimized out>) at ultima.cpp:3080
```

**Comment by vorj** [comment]
@telmin Thank you for reporting.
Unfortunately, the problem didn't occur in our environment.
However, your backtrace told me that `clang::Decl::getAttrs` needs pre-check with `clang::Decl::hasAttrs` .

I fixed the problem in [48-fix-ultima-crash](https://github.com/fixstars/clpy/tree/48-fix-ultima-crash) .
Would you please check and report behavior of ultima in this branch?

**Comment by telmin** [comment]
@vorj 
Thank you. I'll try that branch.

**Comment by telmin** [comment]
@vorj 
I tried 48-fix-ultima-crash. Unfortunately, error is still occurring.
is something wrong with my clang/llvm?
Could you tell me your clang/llvm version please.

- message
```
$ python test_atomicAdd.py
EE
======================================================================
ERROR: test_float32 (__main__.TestAtomicAdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_atomicAdd.py", line 29, in test_float32
    z = kernel(x, y)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 158, in clpy.core.core.compile_with_cache
  File "clpy/core/carray.pxi", line 173, in clpy.core.core.compile_with_cache
clpy.backend.ultima.exceptions.UltimaRuntimeError: Return code:-6
STDERR:
ultima: /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:106: static bool llvm::isa_impl_cl<clang::AnnotateAttr, const clang::Attr *>::doit(const From *) [To = clang::AnnotateAttr, From = const clang::Attr *]: Assertion `Val && "isa<> used on a null pointer"' failed.


======================================================================
ERROR: test_float32_conflict (__main__.TestAtomicAdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_atomicAdd.py", line 53, in test_float32_conflict
    kernel(x, z)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 158, in clpy.core.core.compile_with_cache
  File "clpy/core/carray.pxi", line 173, in clpy.core.core.compile_with_cache
clpy.backend.ultima.exceptions.UltimaRuntimeError: Return code:-6
STDERR:
ultima: /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:106: static bool llvm::isa_impl_cl<clang::AnnotateAttr, const clang::Attr *>::doit(const From *) [To = clang::AnnotateAttr, From = const clang::Attr *]: Assertion `Val && "isa<> used on a null pointer"' failed.


----------------------------------------------------------------------
Ran 2 tests in 0.627s

FAILED (errors=2)
```

- backtrace

```
#0  0x00007fffecf76428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffecf7802a in __GI_abort () at abort.c:89
#2  0x00007fffecf6ebd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x1f32a18 "Val && \"isa<> used on a null pointer\"", file=file@entry=0x1f32a3e "/home/sakamoto/libs/llvm/include/llvm/Support/Casting.h", line=line@entry=106, function=function@entry=0x1f32a76 "static bool llvm::isa_impl_cl<clang::AnnotateAttr, const clang::Attr *>::doit(const From *) [To = clang::AnnotateAttr, From = const clang::Attr *]") at assert.c:92
#3  0x00007fffecf6ec82 in __GI___assert_fail (assertion=0x1f32a18 "Val && \"isa<> used on a null pointer\"", file=0x1f32a3e "/home/sakamoto/libs/llvm/include/llvm/Support/Casting.h", line=106, function=0x1f32a76 "static bool llvm::isa_impl_cl<clang::AnnotateAttr, const clang::Attr *>::doit(const From *) [To = clang::AnnotateAttr, From = const clang::Attr *]") at assert.c:101
#4  0x000000000042a7ae in llvm::isa_impl_cl<clang::AnnotateAttr, clang::Attr const*>::doit (Val=<optimized out>) at /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:106
#5  llvm::isa_impl_wrap<clang::AnnotateAttr, clang::Attr const*, clang::Attr const*>::doit (Val=<optimized out>) at /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:133
#6  llvm::isa_impl_wrap<clang::AnnotateAttr, clang::Attr* const, clang::Attr const*>::doit (Val=<optimized out>) at /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:123
#7  llvm::isa<clang::AnnotateAttr, clang::Attr*> (Val=<optimized out>) at /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:143
#8  llvm::dyn_cast<clang::AnnotateAttr, clang::Attr> (Val=<optimized out>) at /home/sakamoto/libs/llvm/include/llvm/Support/Casting.h:334
#9  ultima::decl_visitor::prettyPrintPragmas<clang::VarDecl> (this=0x36a8780, D=<optimized out>) at ultima.cpp:1849
#10 0x0000000000413c60 in ultima::decl_visitor::VisitVarDecl (this=0x36a8780, D=0x376c600, parameter=true) at ultima.cpp:2605
#11 0x0000000000411670 in ultima::decl_visitor::VisitParmVarDecl (this=<optimized out>, D=<optimized out>) at ultima.cpp:2757
#12 ultima::decl_visitor::VisitFunctionDecl (this=0x36a8780, D=<optimized out>) at ultima.cpp:2360
#13 0x000000000040f334 in ultima::decl_visitor::VisitFunctionTemplateDecl (this=0x36a8780, D=<optimized out>) at ultima.cpp:2987
#14 0x000000000042669a in ultima::decl_visitor::VisitDeclContext (this=<optimized out>, DC=<optimized out>, indent=false) at ultima.cpp:2062
#15 0x00000000009c770d in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false) at /root/llvm/llvm/tools/clang/lib/Parse/ParseAST.cpp:159
#16 0x000000000051d48f in clang::ASTFrontendAction::ExecuteAction (this=0x3666f00) at /root/llvm/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:999
#17 0x000000000051cea4 in clang::FrontendAction::Execute (this=0x3666f00) at /root/llvm/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:897
#18 0x00000000004b01f6 in clang::CompilerInstance::ExecuteAction (this=0x7fffffffcc50, Act=...) at /root/llvm/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:991
#19 0x0000000000450786 in clang::tooling::FrontendActionFactory::runInvocation (this=0x3618830, Invocation=std::shared_ptr (empty) 0x0, Files=0x3619810, PCHContainerOps=std::shared_ptr (empty) 0x0, DiagConsumer=0x0) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:323
#20 0x00000000004505ac in clang::tooling::ToolInvocation::runInvocation (this=0x7fffffffd8c0, BinaryName=0x36193c0 "clang-tool", Compilation=0x3661d00, Invocation=std::shared_ptr (empty) 0x0, PCHContainerOps=std::shared_ptr (empty) 0x0) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:299
#21 0x00000000004503b5 in clang::tooling::ToolInvocation::run (this=0x7fffffffd8c0) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:284
#22 0x0000000000451a3c in clang::tooling::ClangTool::run (this=0x7fffffffdaf0, Action=0x3618830) at /root/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:456
#23 0x000000000040ce1c in main (argc=<optimized out>, argv=<optimized out>) at ultima.cpp:3097
```

**Comment by vorj** [comment]
@telmin 
We use clang 6.0.0. 

```shell-session
$ clang++ --version
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
$ 
```

**Comment by telmin** [comment]
@vorj 
hmm... I used the same version is ...
```
s$ clang++ --version
clang version 6.0.0 (tags/RELEASE_600/final 340153)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Did you install clang/llvm via apt?

**Comment by vorj** [comment]
@telmin No, our clang is built from source codes.

Your libTooling throws errors of "assertion failed".
It seems that our clang skips assertion check, because it is built with Release mode.
I'll test with clang built with Debug mode.

**Comment by telmin** [comment]
@vorj 
Thank you for your information.
I'll build and test clang with Release mode.

**Comment by telmin** [comment]
@vorj 
I rebuilt clang with Release mode and test.
48-fix-ultima-crash got error. but clpy branch worked without error.

this problem was caused by clang build mode, I guess...

**Comment by vorj** [comment]
@telmin Thank you for testing. I need a little more time to set up the environment.

I want to know the error on 48-fix-ultima-crash. Or is the error the same as [this one](https://github.com/fixstars/clpy/issues/48#issuecomment-414604124)?

**Comment by telmin** [comment]
@vorj 
oops, sorry.
the error is the same as that.

**Comment by vorj** [comment]
@telmin I am sorry to have kept you waiting so long.
I set up assertion-enabled clang and confirmed the error.
Finally, I found the bug and fixed it. I think that it works fine.
Please pull the branch and test it.

**Comment by telmin** [comment]
@vorj 
Thank you!
I made sure that 48-fix-ultima-crash works perfectly.
Thank you so much for your support.

**Comment by vorj** [comment]
@telmin 
Thank you for your repoting and patience.
I will make a PR and close this issue.
